apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: rhacs-ci-example-
  namespace: rhacs-ci
spec:
  pipelineRef:
    name: deployment-validation
  params:
  - name: rhacs-api-config-secret-name
    value: rhacs-api-config
  - name: git-url
    value: https://github.com/marcoklaassen/stackrox-ci-notification-demo.git
  - name: git-revision
    value: main
  - name: file-location-in-git-repo
    value: deployment/failing-deployment.yaml
  workspaces:
    - name: files
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Mi
